### PR TITLE
creating account...TypeError: cb is not a function

### PR DESCRIPTION
**Pull request by scenaristeur**

### CODE REVIEW

**Review by scenaristeur — COMMENTED** [review]
creating account...
TypeError: cb is not a function

**Review by scenaristeur — COMMENTED** [review]
creating account...
TypeError: cb is not a function

**Comment by diatche** [comment]
Thanks for opening a PR, will review soon

**Comment by diatche** [comment]
The issue was in the `auth.cb`, which has been fixed in #34. Thanks anyway!

**Pull request closed without merging**
